# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
---
include:
### Splitent ###
#  - board: seeeduino_xiao_ble
#    shield: splitent_left
#  - board: seeeduino_xiao_ble
#    shield: splitent_right
#  - board: seeeduino_xiao_ble
#    shield: settings_reset
### Maglit40ble ###
#  - board: seeeduino_xiao_ble
#    shield: maglit40_left
#    snippet: studio-rpc-usb-uart
#  - board: seeeduino_xiao_ble
#    shield: maglit40_right
#  - board: seeeduino_xiao_ble
#    shield: settings_reset
### nox40 ###
  - board: seeeduino_xiao_ble
    shield: nox40_left
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: nox40_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
