# SPDX-License-Identifier: MIT
description: Custom battery status behavior

compatible: "zmk,behavior-battery-status"

include: "zmk,behavior.yaml"

properties:
  label:
    type: string
    required: true
