# SPDX-License-Identifier: MIT
description: Custom battery status behavior

compatible: "zmk,behavior-battery-status"

include: "behavior-metadata.yaml"

properties:
  label:
    type: string
    required: true
